#!/bin/bash
for FILE in ~/.zshrc ~/.bashrc ~/.bash_profile
do
    if [[ -f "$FILE" ]]; then
        if ! grep -q SEAD_HOME $FILE
        then
            echo  >> $FILE
            echo "# SEAD" >> $FILE
            echo "export SEAD_HOME=~/devel/SEAD" >> $FILE
            source $FILE
        fi
    fi
done

export SEAD_HOME=~/devel/SEAD

echo $SEAD_HOME
mkdir -p $SEAD_HOME


if [ ! -d "$SEAD_HOME/bin" ]; then
    git clone git@github.com:suap-ead/bin.git $SEAD_HOME/bin
fi

cd $SEAD_HOME/bin

echo ""
echo "--- UNDEPLOY ----"
./undeploy


echo ""
echo "--- DEPLOY ---"
./deploy
