#!/bin/bash

if [[ -f ~/.bashrc ]]; then
    if ! grep -q SEAD_HOME ~/.zshrc; then;
        echo  >> ~/.bashrc
        echo "# SEAD" >> ~/.bashrc
        echo "export SEAD_HOME=~/devel/SEAD" >> ~/.bashrc
        source ~/.bashrc
    fi
fi

if [[ -f ~/.zshrc ]]; then
    if ! grep -q SEAD_HOME ~/.zshrc; then;
        echo  >> ~/.zshrc
        echo "# SEAD" >> ~/.zshrc
        echo "export SEAD_HOME=~/devel/SEAD" >> ~/.zshrc
        source ~/.zshrc
    fi
fi

export SEAD_HOME=~/devel/SEAD

echo $SEAD_HOME
mkdir -p $SEAD_HOME


if [ ! -d "$SEAD_HOME/bin" ]; then
    git clone git@github.com:suap-ead/bin.git $SEAD_HOME/bin
fi

cd $SEAD_HOME/bin

echo ""
echo "--- DEPLOY ----"
./undeploy


echo ""
read -r "Você deseja fazer o DEPLOY? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
    ./deploy
else
    echo "Skipped"
fi
